# Generated by Django 5.0.6 on 2026-05-11 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules pour faciliter la recherche', max_length=500, verbose_name='Mots-clés')),
                ('category', models.CharField(default='Général', help_text='Ex: Réseau, Hardware, Software, Sécurité...', max_length=100, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('source', models.CharField(choices=[('FAQ', 'Base de connaissances FAQ'), ('OPENAI', 'API ChatGPT'), ('ERROR', 'Erreur')], default='FAQ', max_length=10, verbose_name='Source de la réponse')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('faq_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_messages', to='chat.faq', verbose_name='FAQ utilisée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConvHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='chat.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Historique de conversation',
                'verbose_name_plural': 'Historiques de conversations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
